import EStyleSheet from "react-native-extended-stylesheet";

export default EStyleSheet.build({
  $TINT_COLOR_PRIMARY: "#002859",
  $TINT_COLOR_SECONDARY: "#647184",
  $BACKGROUND_COLOR: "#FFFFFF",

  $BUTTON_BACKGROUND_COLOR: "#035AC5",
  $BUTTON_TEXT_COLOR: "#FFFFFF",

  $SECONDARY_BUTTON_BACKGROUND_DISABLED: "#F9FAFC",

  $BUTTON_BACKGROUND_COLOR_DISABLED: "#EAF3FF",
  $BUTTON_TEXT_COLOR_DISABLED: "#71B0FD",
  $LITTLE_BUTTON_BACKGROUND: "#EFF2F7",

  $INACTIVE_TEXT_COLOR: "#C0CCDA",

  $INPUT_BORDER_COLOR: "#E5E9F2",
  $INPUT_FOCUS_BORDER_COLOR: "#035AC5",
});
